-- Steps:

-- 1. Create database named "Animals".
-- In Oracle, you typically don't create databases in the same way as in SQL Server.
-- Instead, you create a user/schema. 

CREATE USER Animals IDENTIFIED BY password;
GRANT CONNECT, RESOURCE TO Animals;

-- Connect as the Animals user.
ALTER SESSION SET CURRENT_SCHEMA = Animals;

-- 2. Create table named "Mammals" with columns "Id" and "Name".

CREATE TABLE Mammals (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    Name VARCHAR2(50)
);

-- 3. Fill out the table with the following animals:
-- Blue Whale, Camel, Rhino, Bison, Giraffe,
-- Polar Bear, Elephant, Dolphin, Zebra, Tiger
-- Hippopotamus, Lion, Gorilla, Wolf, Kangaroo

INSERT INTO Mammals (Name) VALUES ('Blue Whale');
INSERT INTO Mammals (Name) VALUES ('Camel');
INSERT INTO Mammals (Name) VALUES ('Rhino');
INSERT INTO Mammals (Name) VALUES ('Bison');
INSERT INTO Mammals (Name) VALUES ('Giraffe');
INSERT INTO Mammals (Name) VALUES ('Polar Bear');
INSERT INTO Mammals (Name) VALUES ('Elephant');
INSERT INTO Mammals (Name) VALUES ('Dolphin');
INSERT INTO Mammals (Name) VALUES ('Zebra');
INSERT INTO Mammals (Name) VALUES ('Tiger');
INSERT INTO Mammals (Name) VALUES ('Hippopotamus');
INSERT INTO Mammals (Name) VALUES ('Lion');
INSERT INTO Mammals (Name) VALUES ('Gorilla');
INSERT INTO Mammals (Name) VALUES ('Wolf');
INSERT INTO Mammals (Name) VALUES ('Kangaroo');

-- 4. Select all animals in alphabetical order

SELECT Name
FROM Mammals
ORDER BY Name ASC;

-- 5. 10-th position is a Secret Key

SELECT Name AS SecretKey
FROM (SELECT Name, ROW_NUMBER() OVER (ORDER BY Name) AS rn FROM Mammals)
WHERE rn = 10;
